# Generated by Django 2.0.6 on 2018-06-14 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20180614_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='createBy',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
